name: release

# on:
#   release:
#     types: [created]

on:
  push:
    tags:
      - "*"

jobs:
  releases-matrix:
    name: Release Go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: amd64
        # goarch: [amd64, arm]
        # goarch: ["386", amd64, arm]
        # exclude:
          # - goarch: "386"
          #   goos: darwin
          # - goarch: arm
          #   goos: windows

    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.17
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/progszy"
          binary_name: "progszy"
          extra_files: LICENSE.md README.md

      # # Install dependencies
      # - name: Install dependencies
      #   run: |
      #     go version
      #     go get -t -v ./...

      # # Build project
      # - name: Build project
      #   run: go build ./...
