name: release

on:
  push:
    tags:
      # - "v*.*.**"
      - "*"

jobs:
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # - uses: actions/checkout@v2
      # - uses: wangyoucao577/go-release-action@v1.17
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     goos: ${{ matrix.goos }}
      #     goarch: ${{ matrix.goarch }}
      #     project_path: "./cmd/progszy"
      #     binary_name: "progszy"
      #     extra_files: LICENSE.md README.md

