name: release

on:
  push:
    tags:
      - "v*.*.**"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'stable'

    - name: Install cross-compilers
      run: sudo apt-get install gcc-mingw-w64 gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
